import './global.css';
import { ThemeModeScript } from 'flowbite-react';
import { StoreInit as ThemeInit } from 'flowbite-react/store/init';

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ThemeModeScript />
      </head>
      <body>
        <ThemeInit dark prefix="" version={3} />
        {children}
      </body>
    </html>
  );
}
